#include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_INPUT_CAPELLA_CM36686)     += cm36686.o
#ifeq ($(CONFIG_ARCH_MTK_PROJECT),"v36bml")
#EXTRA_CFLAGS += -DNO_GPIO_NFC_ENABLE
#endif
